// DO NOT EDIT THIS FILE!!!!!!!
// Please edit the JSON file, or the enviorment variables to change the configuration.
// This is for processing your configuration, and changing this can cause problems.

package main

import (
	"os"
	"strconv"
	"encoding/json"
)

type Config struct {
	// Accessible server address
	URL string `json:"address"` // TODO: phase this out in favor of getting "host" from the http request?
	// The port to run the server on
	Port int `json:"port"`
}

// Parse config from first environment variables, then the config.json file
func ParseConfig() Config {
    // Set default values
    config := Config{
        URL:  "https://localhost:3000",
        Port: 3000,
    }

	// Read config from config.json file
	file, err := os.Open("config.json")
	if err == nil {
		defer file.Close()
		decoder := json.NewDecoder(file)
		fileConfig := Config{}
		if err := decoder.Decode(&fileConfig); err == nil {
			if fileConfig.URL != "" {
				config.URL = fileConfig.URL
			}
			if fileConfig.Port != 0 {
				config.Port = fileConfig.Port
			}
		}
	}

    // Get values from environment variables
    if url := os.Getenv("SERVER_URL"); url != "" {
        config.URL = url
    }

    if port := os.Getenv("SERVER_PORT"); port != "" {
        if portInt, err := strconv.Atoi(port); err == nil {
            config.Port = portInt
        }
    }

    return config
}