# The CDN_URL is the URL send to clients to access images from this server.
# Set it to where the server can be accessed from your device.
# You can test this by going to the CDN_URL in your device web browser and
# seeing if it loads
# DO NOT ADD A TRAILING SLASH
# GOOD http://127.0.0.1:3000
# BAD: http://127.0.0.1:3000/
CDN_URL: 'http://127.0.0.1:3000'

# The URL that will be displayed in the text
# This is the URL that will be displayed in the text of the tweet
# This is not the link seen by the viewer, not where it will actually go to.

# You can also set it to nothing if you don't want a URL to be displayed.
# This does break older clients, and has a useless URL area in the tweet.

# {shortblob} is the last few letters of the bluesky cdn blob
# {fullblob} is the full bluesky blob
# {user_did} is the image owner's DID 

IMG_DISPLAY_TEXT: 'pic.twitter.com/{shortcode}'

# Now this link is where it actually will go to (sometimes), although this is not displayed to the user*
# IMG_URL_TEXT: 'http://127.0.0.1:3000/cdn/img/bsky/{user_did}/{fullblob}.jpg' # if you don't want to do any redirects, it will eventually arrive here.
IMG_URL_TEXT: 'http://127.0.0.1:3000/img/{shortcode}' # if you want to do a redirect, and have it be short, it should arrive here.

# Same as the above, but for videos
VID_DISPLAY_TEXT: 'pic.twitter.com/{shortcode}'

# Same as the above (again), but for videos
VID_URL_TEXT: 'http://127.0.0.1:3000/img/{shortcode}'


# SERVER_PORT is the port the server will listen on.
SERVER_PORT: 3000

# This database stores:
# Analytics (if enabled)
# User DID, PDS, session UUID and tokens (tokens are encrypted with key contained in oauth header provided by clients)
# Bluesky contexts

# Database Type (sqlite, mysql, postgres)
DATABASE_TYPE: 'sqlite'

# Database Path/DSN (see https://gorm.io/docs/connecting_to_the_database.html)
DATABASE_PATH: './db/twitterbridge.db'

# TRACK_ANALYTICS toggles whether analytics should be tracked and stored in the database
# This tracks (anonomized):
# Twitter version used to connect
# Useragent of the client
# How many people have logged on
# How many tweets have been sent to bluesky
# How many tweets have been sent to clients
# IP address (for country location data)
# Language
# more probably to come
TRACK_ANALYTICS: true

# Enable this if behind a reverse proxy
USE_X_FORWARDED_FOR: false

# DEVELOPER_MODE
# This is used to enable some extra logging useful during development.
# DO NOT ENABLE THIS IN A PUBLIC INSTANCE!!!
DEVELOPER_MODE: false